In [3]:
import numpy as np

In [4]:
#1. Write code to create a 4x3 matrix with values ranging from 2 to 13.
arr1 = np.arange(2, 14).reshape(4, 3)
print("1. 4x3 Matrix:")
print(arr1)

1. 4x3 Matrix:
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]
 [11 12 13]]


In [8]:
# 2. Replace odd numbers by -1 in an array created using random.randint(1, 50, 20)
arr2 = np.random.randint(1, 50, 20)
print("Original Array:")
print(arr2)

arr2[arr2 % 2 != 0] = -1
print("Array after replacing odd numbers with -1:")
print(arr2)

Original Array:
[44 20 26  7 29 23 41 42 42 47 14  7 28 48 39 19 37 44 28 16]
Array after replacing odd numbers with -1:
[44 20 26 -1 -1 -1 -1 42 42 -1 14 -1 28 48 -1 -1 -1 44 28 16]


In [12]:
# 3. Mobile phone prices operations
prices = np.array([6999, 7500, 11999, 27899, 14999, 9999])

# a. Create 1D array
print("Mobile Prices Array:")
print(prices)

Mobile Prices Array:
[ 6999  7500 11999 27899 14999  9999]


In [14]:
# b. Convert to float type
prices = prices.astype(float)
print("Converted to Float:")
print(prices)

Converted to Float:
[ 6999.  7500. 11999. 27899. 14999.  9999.]


In [15]:
# c. Append new mobile price 13999
prices = np.append(prices, 13999)
print("After Appending 13999:")
print(prices)

After Appending 13999:
[ 6999.  7500. 11999. 27899. 14999.  9999. 13999.]


In [16]:
# d. Reverse the array
prices = prices[::-1]
print("Reversed Array:")
print(prices)

Reversed Array:
[13999.  9999. 14999. 27899. 11999.  7500.  6999.]


In [17]:
# e. Apply GST of 18%
prices = prices * 1.18
print("After Applying 18% GST:")
print(prices)

After Applying 18% GST:
[16518.82 11798.82 17698.82 32920.82 14158.82  8850.    8258.82]


In [18]:
# f. Sort in descending order
prices = np.sort(prices)[::-1]
print("Sorted in Descending Order:")
print(prices)

Sorted in Descending Order:
[32920.82 17698.82 16518.82 14158.82 11798.82  8850.    8258.82]


In [19]:
# g. Average mobile phone price
avg_price = np.mean(prices)
print("Average Price:", avg_price)

Average Price: 15743.560000000001


In [20]:
# h. Difference between maximum and minimum price
difference = np.max(prices) - np.min(prices)
print("Difference between Max and Min Price:", difference)

Difference between Max and Min Price: 24662.0


In [21]:
# 4. Find indices of non-zero elements
arr4 = np.array([1, 2, 0, 0, 4, 0])
indices = np.nonzero(arr4)
print("\n4. Indices of Non-Zero Elements:")
print(indices)


4. Indices of Non-Zero Elements:
(array([0, 1, 4]),)
