In [1]:
import numpy as np

In [3]:
# 1. Create a NumPy array containing integers from 0 to 9
arr1 = np.arange(10)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
# 2. Create a NumPy array from a Python list
arr2 = np.array([10, 20, 30, 40, 50])
print(arr2)

[10 20 30 40 50]


In [5]:
# 3. Create a 3x3 array with values ranging from 0 to 8
arr3 = np.arange(9).reshape(3, 3)
print(arr3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [6]:
# 4. Create a 5x4 array with random integers between 1 and 100
arr4 = np.random.randint(1, 101, (5, 4))
print(arr4)
print("Shape:", arr4.shape)
print("Size:", arr4.size)

[[ 1 89 44 86]
 [85 85 13 25]
 [68 83  1 38]
 [65 28 54 59]
 [61 99 66 17]]
Shape: (5, 4)
Size: 20


In [7]:
# 5. Create a 3x3 array and access elements
arr5 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

print(arr5[0, 1])
print(arr5[1, 2])
print(arr5[:2, 1:])

2
6
[[2 3]
 [5 6]]


In [8]:
# 6. Create a 1D array of 12 elements and reshape to 3x4
arr6 = np.arange(1, 13)
arr6_reshaped = arr6.reshape(3, 4)
print(arr6_reshaped)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [9]:
# 7. Reshape a 3x3 matrix into a 1D array
arr7 = np.arange(1, 10).reshape(3, 3)
arr7_flat = arr7.reshape(-1)
print(arr7_flat)

[1 2 3 4 5 6 7 8 9]


In [10]:
# 8. Element-wise operations
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2 = np.array([[7, 8, 9],
                 [10, 11, 12]])

print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)

[[ 8 10 12]
 [14 16 18]]
[[-6 -6 -6]
 [-6 -6 -6]]
[[ 7 16 27]
 [40 55 72]]
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [11]:
# 9. Sum, Mean and Standard Deviation
arr9 = np.array([10, 20, 30, 40, 50])

print(np.sum(arr9))
print(np.mean(arr9))
print(np.std(arr9))

150
30.0
14.142135623730951


In [12]:
# 10. Matrix Multiplication
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print(np.dot(A, B))

[[19 22]
 [43 50]]


In [14]:
# 11. Transpose of matrices
print(A.T)
print(B.T)

[[1 3]
 [2 4]]
[[5 7]
 [6 8]]


In [15]:
# 12. Broadcasting
arr12 = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

b = np.array([10, 20, 30])

result = arr12 + b
print(result)

[[11 22 33]
 [14 25 36]
 [17 28 39]]


In [16]:
# 13. Maximum, Minimum and Mean of a 4x4 random array
arr13 = np.random.randint(1, 101, (4, 4))
print(arr13)
print(np.max(arr13))
print(np.min(arr13))
print(np.mean(arr13))

[[82 80 24 12]
 [92 74 36 50]
 [77 83 52 99]
 [38 21 47  1]]
99
1
54.25


In [17]:
# 14. Row-wise and Column-wise sums
print(np.sum(arr13, axis=1))
print(np.sum(arr13, axis=0))

[198 252 311 107]
[289 258 159 162]


In [18]:
# 15. Generate an array of 10 random integers between 1 and 50
arr15 = np.random.randint(1, 51, 10)
print(arr15)

[30 38 29  9  5 23 10 22 31  1]


In [19]:
# 16. Generate a 5x5 matrix of random floats between 0 and 1
arr16 = np.random.rand(5, 5)
print(arr16)

[[0.06287553 0.99786913 0.6339405  0.26847318 0.90999096]
 [0.15016055 0.69870255 0.50637837 0.4135089  0.93678358]
 [0.67364607 0.18457298 0.97887882 0.2273671  0.89107597]
 [0.52699575 0.88696659 0.4968631  0.44118065 0.88995796]
 [0.50834545 0.11459742 0.00631308 0.09858344 0.32230076]]
