In [5]:
import numpy as np
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [6]:
arr.size 

5

In [7]:
arr.dtype

dtype('int64')

In [8]:
arr.ndim

1

In [9]:
arr1 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [10]:
print(arr1.shape)
print(arr1.ndim)
print(arr1.dtype)
print(arr1.size)

(3, 5)
2
int64
15


In [11]:
arr[[0,2,4]]

array([1, 3, 5])

In [12]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [13]:
list1 = [1,2,3,4,5]
list2 = [10,20,30,40,50]
result = list1+list2  
result

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [14]:
a1 = np.array(list1)
a2 = np.array(list2)
result = a1 + a2
print(a1)
print(a2)
print(result)

[1 2 3 4 5]
[10 20 30 40 50]
[11 22 33 44 55]


In [15]:
result = a2 - a1
print(result)

[ 9 18 27 36 45]


In [16]:
result = a1 * a2
print(result)

[ 10  40  90 160 250]


In [17]:
distance = [100,230,120,340,500]
time = [4,5,6,10,4]
speed = []
for i in range(len(distance)):
  speed.append(distance[i]/time[i])
print(speed)

[25.0, 46.0, 20.0, 34.0, 125.0]


In [18]:
np_distance = np.array(distance)
np_time = np.array(time)
np_speed = np_distance / np_time
np_speed

array([ 25.,  46.,  20.,  34., 125.])

In [20]:
#Size of one element
import sys
print("Size of one element : ",sys.getsizeof(list1[0]))
print("Size of entire list : ",sys.getsizeof(list1))

Size of one element :  28
Size of entire list :  104


In [21]:
print("Size of one element :",a1.itemsize)
print("Size of entire array :",a1.itemsize * a1.size)

Size of one element : 8
Size of entire array : 40


In [22]:
%%time
list1 = list(range(1,10000))
list2 = list(range(1,10000))
for i in range(1,1000):
  for j in range(len(list1)):
    list1[j] * list2[j]

CPU times: total: 2.09 s
Wall time: 2.18 s


In [23]:
%%time
arr1 = np.array(list1)
arr2 = np.array(list2)
arr1 *arr2

CPU times: total: 0 ns
Wall time: 1.85 ms


array([       1,        4,        9, ..., 99940009, 99960004, 99980001],
      shape=(9999,))