In [5]:
import numpy as np
range(1,11)

range(1, 11)

In [4]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr = np.linspace(1,20,10)
arr

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [8]:
#A uniform distribution is a probability distribution where every possible outcome or value in a specific range has the exact same likelihood of occurring
np.random.rand(5,4)

array([[0.92030462, 0.15287727, 0.54593026, 0.80211675],
       [0.34376067, 0.69195064, 0.36721151, 0.23238383],
       [0.34242452, 0.81669481, 0.12097202, 0.92436206],
       [0.88580419, 0.18736343, 0.17661531, 0.83629978],
       [0.29553429, 0.22948192, 0.16841941, 0.53240079]])

In [9]:
#We get specified number of random integers between start and stop value
np.random.randint(1000,10000,50)

array([1923, 8543, 7406, 8322, 6590, 1237, 9013, 8887, 2828, 8599, 7125,
       9887, 7188, 1503, 4879, 5783, 2788, 1731, 6940, 7878, 8101, 7928,
       9803, 8894, 2067, 9735, 6105, 5821, 9656, 8408, 9247, 9026, 3806,
       5609, 3714, 7153, 1176, 4072, 3291, 7330, 1201, 3033, 6586, 2418,
       1159, 6866, 8856, 4446, 4877, 2605], dtype=int32)

In [10]:
#normal distribution (also called a Gaussian distribution or bell curve) is a continuous probability distribution where data is symmetrically clustered around the mean. In this distribution, most data points gather near the center, and occurrences taper off equally on both sides
np.random.randn(5)

array([ 0.73703242, -1.14431394, -1.11440433,  0.37459993,  2.69432746])

In [11]:
np.zeros([4,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones([4,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
a1 = np.arange(1,5)
a1

array([1, 2, 3, 4])

In [14]:
a1  =  a1.reshape(2,2)
a1

array([[1, 2],
       [3, 4]])

In [15]:
a2 = np.arange(5,9).reshape(2,2)
a2

array([[5, 6],
       [7, 8]])

In [16]:
np.dot(a1,a2)

array([[19, 22],
       [43, 50]])

In [17]:
np.matmul(a1,a2)

array([[19, 22],
       [43, 50]])

In [18]:
np.linalg.det(a1)

np.float64(-2.0000000000000004)

In [19]:
np.matmul(a1,a2)

array([[19, 22],
       [43, 50]])

In [20]:
np.linalg.det(a1)

np.float64(-2.0000000000000004)

In [21]:
np.linalg.det(a2)

np.float64(-2.000000000000005)